#!/bin/bash

echo "🔐 Setting up authentication for Google Merchant/Product Studio API"
echo "=================================================================="
echo ""
echo "The Product Studio API requires OAuth authentication with the 'content' scope."
echo ""
echo "To set this up, run:"
echo ""
echo "1. Authenticate with the content scope:"
echo "   gcloud auth application-default login --scopes=\"https://www.googleapis.com/auth/content,https://www.googleapis.com/auth/cloud-platform\""
echo ""
echo "2. Or use regular auth and specify scopes:"
echo "   gcloud auth login --scopes=\"https://www.googleapis.com/auth/content\""
echo ""
echo "3. Then test the API again"
echo ""
echo "Note: You may also need to:"
echo "- Link your Google Cloud project to your Merchant Center account"
echo "- Request access to the Product Studio v1alpha API (it's in preview)"
echo "- Check https://merchants.google.com/mc/settings to configure API access"